# Generated by Django 4.2.5 on 2023-09-26 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MRTLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="station",
            name="station_codes",
        ),
        migrations.CreateModel(
            name="MRTLineStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_code", models.CharField(max_length=5)),
                (
                    "mrt_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="main.mrtline",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.station"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="station",
            name="train_line_stations",
            field=models.ManyToManyField(
                through="main.MRTLineStation", to="main.mrtline"
            ),
        ),
    ]
