# Generated by Django 4.2.5 on 2023-09-26 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_remove_mrtline_prefix"),
    ]

    operations = [
        migrations.RenameField(
            model_name="station",
            old_name="station_name",
            new_name="name",
        ),
    ]
