# Generated by Django 4.2.5 on 2023-09-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_rename_station_name_station_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="affected_stations",
            field=models.ManyToManyField(
                through="main.IncidentAffectedStation",
                to="main.station",
                verbose_name="affected station(s)",
            ),
        ),
        migrations.AlterField(
            model_name="incidentreport",
            name="affected_stations",
            field=models.ManyToManyField(
                through="main.IncidentReportAffectedStation",
                to="main.station",
                verbose_name="affected station(s)",
            ),
        ),
        migrations.AlterField(
            model_name="majordisruption",
            name="affected_stations",
            field=models.ManyToManyField(
                through="main.DisruptionAffectedStation",
                to="main.station",
                verbose_name="affected station(s)",
            ),
        ),
    ]
