# Generated by Django 4.2.5 on 2023-09-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_incident_affected_stations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="affected_stations",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="description",
        ),
        migrations.AlterField(
            model_name="disruptionaffectedstation",
            name="disruption",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disruption_affected_stations",
                to="main.majordisruption",
            ),
        ),
        migrations.AlterField(
            model_name="disruptionaffectedstation",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disruption_affected_stations",
                to="main.station",
            ),
        ),
        migrations.AlterField(
            model_name="incidentreportaffectedstation",
            name="incident_report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_report_affected_stations",
                to="main.incidentreport",
            ),
        ),
        migrations.AlterField(
            model_name="incidentreportaffectedstation",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_report_affected_stations",
                to="main.station",
            ),
        ),
        migrations.AlterField(
            model_name="mrtlinestation",
            name="mrt_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_stations",
                to="main.mrtline",
            ),
        ),
        migrations.AlterField(
            model_name="mrtlinestation",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_stations",
                to="main.station",
            ),
        ),
        migrations.DeleteModel(
            name="IncidentAffectedStation",
        ),
    ]
