# Generated by Django 4.2.5 on 2023-09-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_incidentreport_incident"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incidentreport",
            name="affected_stations",
        ),
        migrations.AddField(
            model_name="incident",
            name="station",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.station",
            ),
            preserve_default=False,
        ),
    ]
