# Generated by Django 4.2.5 on 2023-10-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_congestion_incident_resolved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="stations",
            field=models.ManyToManyField(to="main.station"),
        ),
    ]
