# Generated by Django 4.2.5 on 2023-10-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_notificationpreference_day_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congestionforecast',
            name='added_at',
        ),
    ]
