# Generated by Django 4.2.5 on 2023-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_congestionforecast_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majordisruption',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
