# Generated by Django 4.2.5 on 2023-10-31 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_alter_congestionforecast_station_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mrtline",
            name="code",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="congestion",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="congestion_ratings",
                to="main.mrtlinestation",
            ),
        ),
    ]
