# Generated by Django 4.2.5 on 2023-10-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_mrtline_code_alter_congestion_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mrtline",
            name="code",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
