# Generated by Django 4.2.5 on 2023-10-31 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_announcement_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="station",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.station",
            ),
        ),
    ]
